### PR TITLE
Added code of conduct file.

### PR DESCRIPTION
**Pull request by Kris248**
Just a code of conduct file. You can merge it if there's a need of this file in this project.

### CODE REVIEW

**Comment by biplobsd** [comment]
Great @Kris248 can you add this file in the `.github` directory? https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

Also can you mension this file in the `README.md` file somewhere section?

**Review by biplobsd — CHANGES_REQUESTED** [review]
- `.github/`
- `README.md`

**Comment by Kris248** [comment]
updated

**Comment by biplobsd** [comment]
@Kris248 Thanks for contributed to the `OneClickRun`

**Pull request merged**
