### PR TITLE
Added MultiUpload and fixed logos

### PR DESCRIPTION
**Pull request by bunnykek**
I have added a new cell using which a user can upload a file to 15+ free hosting services.
The core app is made by Sorrow, I have just implemented it in your notebook.

### CODE REVIEW

**Comment by bunnykek** [comment]
image

**Comment by biplobsd** [comment]
@bunnykek Thank you for contributing to OneClickRun.

**Comment by biplobsd** [comment]
@bunnykek Can you somehow clear the error text and then print successfully install MultiUpload ? This is can on new user confused to use this cell..

image

And also create a tools/multiupload/ to store your all installation, configuration files in tools directory? This will cleanup look for /content directory.

**Comment by bunnykek** [comment]
image

**Pull request merged**
