### PR TITLE
Resolved #37 - removed X86_64 from PACKAGES and set default amd64

### LINKED ISSUE #37: code-server x86_64 installation file not found!
Just remove X86_64 from PACKAGES and set default amd64. You can find on code-server cell.
image
Then just create a pull request and referring this issues tag number #... .

### PR DESCRIPTION
**Pull request by Indrajeet-S**
Solved issue #37

### CODE REVIEW

**Comment by biplobsd** [comment]
@Indrajeet-S Thank you for contributing to OneClickRun.
Could you just set PACKAGES value amd64.
Example:
`PACKAGES = "amd64"`
<strike>`PACKAGES = "amd64" #@param ["x86_64", "amd64"]`</strike>

Because we don't need x86_64 anymore 🙂

**Comment by Indrajeet-S** [comment]
> @Indrajeet-S Thank you for contributing to OneClickRun. Could you just set PACKAGES value amd64. Example: `PACKAGES = "amd64"` `PACKAGES = "amd64" #@param ["x86_64", "amd64"]`
> 
> Because we don't need x86_64 anymore 🙂

Should I make this change now? or else... @biplobsd

**Comment by biplobsd** [comment]
Yes if you can. Please

**Comment by Indrajeet-S** [comment]
Hey @biplobsd 
I made another commit "made changes as discussed" but is it going something wrong.. since I am not getting what it is..

**Comment by biplobsd** [comment]
@Indrajeet-S ok I'll resolve the conflict. Thanks you again for contributing to OneClickRun 🔥🔥

**Comment by Indrajeet-S** [comment]
> @Indrajeet-S ok I'll resolve the conflict. Thanks you again for contributing to OneClickRun 🔥🔥

Thank you so much @biplobsd

**Comment by biplobsd** [comment]
If you want, there are more issues you can solve. This project is open to everyone. 💥🔥

**Pull request merged**
