### PR TITLE
fix #57 pul request template

### LINKED ISSUE #57: Create a pull request template file
The pull request template includes - 
- Summary
  - Fixes issues hash number
- Category
- Screenshots or GIFs (if applicable)
- Additional Information (optional)

How to create a pull request template? 
check out: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### PR DESCRIPTION
**Pull request by carlospatinos**
Issue:
fix #57

Category: #hacktoberfest

Screenshot: not applicable

### CODE REVIEW

**Comment by biplobsd** [comment]
Hey @carlospatinos, the template location is not in the root.. Follow this instruction properly:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

image

**Comment by carlospatinos** [comment]
Appologies, where do you want the template? in the screenshot above it gives the option to be in the root, inside docs, etc i did not see any particular path as part of the issue description but happy to put it wherever you want. Can you please let me know. Thanks

**Comment by biplobsd** [comment]
Create `.github/` directory and put it on

**Comment by carlospatinos** [comment]
File has been now moved to .github location. thanks

**Comment by biplobsd** [comment]
Thanks @carlospatinos for the PR. Happy hacktoberfest.

**Comment by carlospatinos** [comment]
Thanks for letting me contribute. Have a good one

**Pull request merged**
